# Generated by Django 3.2.6 on 2021-10-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignupApp', '0004_tmsuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmsuser',
            name='pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
    ]
