# Generated by Django 3.2.6 on 2021-10-22 06:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SignupApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('pname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pdetails', models.TextField(blank=True, default='no package details provided !', max_length=200)),
                ('pic', models.ImageField(default='pdefault.jpg', upload_to='package_pics')),
                ('amount', models.CharField(default='1000', max_length=5)),
                ('ptype', models.CharField(choices=[('common', 'Common'), ('special', 'Special'), ('luxury', 'Luxury')], default='common', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TMSBooking',
            fields=[
                ('booking_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('no_of_person', models.PositiveIntegerField(default=1)),
                ('amount', models.PositiveIntegerField()),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BookTicketApp.packagedetails')),
                ('tmsuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SignupApp.tmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=200)),
                ('tmsuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SignupApp.tmsuser')),
            ],
        ),
    ]
