# Generated by Django 3.2.6 on 2021-10-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='pdestination',
            field=models.CharField(default='no location given', max_length=20),
        ),
    ]
