# Generated by Django 3.2.6 on 2021-10-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedetails',
            name='amount',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
