# Generated by Django 3.2.6 on 2021-10-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0004_rename_feedback_feedback_feedback_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_comment',
            new_name='feedback',
        ),
    ]
