# Generated by Django 3.2.6 on 2021-10-20 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0005_rename_feedback_comment_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='ptype',
            field=models.CharField(choices=[('common', 'Common'), ('special', 'Special'), ('luxury', 'Luxury')], default='common', max_length=10),
        ),
        migrations.AlterField(
            model_name='tmsbooking',
            name='departure_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tmsbooking',
            name='no_of_person',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
