# Generated by Django 3.2.6 on 2021-10-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicketApp', '0006_auto_20211020_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='pdetails',
            field=models.TextField(default='no package details provided !', max_length=200),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='pic',
            field=models.ImageField(default='pdefault.jpg', upload_to='package_pics'),
        ),
        migrations.AlterField(
            model_name='packagedetails',
            name='amount',
            field=models.CharField(default='1000', max_length=5),
        ),
    ]
