# Generated by Django 3.2.6 on 2021-10-23 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('docId', models.AutoField(primary_key=True, serialize=False)),
                ('docType', models.CharField(choices=[('Passport', 'Passport'), ('Adhar', 'Adhar'), ('voter-Id', 'Voter-Id'), ('pan-card', 'PAN Card'), ('driving-licencse', 'Driving-licencse'), ('Flight-ticket', 'Flight-Ticket'), ('Hotel-reservation', 'Hotel-Reservation'), ('Other-document', 'Other')], max_length=45, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('expDate', models.DateField(default=django.utils.timezone.now)),
                ('docImg', models.FileField(default='docImg_default.png', upload_to='documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
