# Generated by Django 3.2.6 on 2021-10-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docImg',
            field=models.FileField(default='docImg_default.png', upload_to='documents'),
        ),
    ]
