# Generated by Django 3.2.6 on 2021-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentApp', '0002_alter_document_docimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docType',
            field=models.CharField(choices=[('Passport', 'Passport'), ('Adhar', 'Adhar'), ('voter-Id', 'Voter-Id'), ('pan-card', 'PAN Card'), ('driving-licencse', 'Driving-licencse'), ('Flight-ticket', 'Flight-Ticket'), ('Hotel-reservation', 'Hotel-Reservation'), ('Other-document', 'Other')], max_length=45, null=True),
        ),
    ]
